#include <gtest/gtest.h>
#include <io/param_reader.h>

using namespace NJRobot;


TEST(io,paramRead){
	std::string file = "./resource/test.xml";
	LOAD_PARAM_FROM_XML(file.c_str());

	bool BOOL1,BOOL2,BOOL3,BOOL4;
	int INT1,INT2,INT3;
	double DOUBLE1,DOUBLE2;
	std::string STR1;

	DECLARE_PARAM_READER_BEGIN(Field1)
		READ_PARAM(BOOL1)
		READ_PARAM(BOOL2)
		READ_PARAM(BOOL3)
		READ_PARAM(BOOL4)
		READ_PARAM(INT1)
		READ_PARAM(INT2)
		READ_PARAM(INT3)
		READ_PARAM(DOUBLE1)
		READ_PARAM(DOUBLE2)
		READ_PARAM(STR1)
	DECLARE_PARAM_READER_END
	
	EXPECT_TRUE(BOOL1);
	EXPECT_FALSE(BOOL2);
	EXPECT_FALSE(BOOL3);
	EXPECT_FALSE(BOOL4);
	EXPECT_EQ(INT1,-123);
	EXPECT_EQ(INT2,1);
	EXPECT_EQ(INT3,1);
	EXPECT_FLOAT_EQ(DOUBLE1,0.00123);
	EXPECT_FLOAT_EQ(DOUBLE2,1234567890);
	EXPECT_STREQ(STR1.c_str(),"abc123.4_5 \\\\.\\com5 192.168.0.1 0.015 0.0 0");


	DECLARE_PARAM_READER_BEGIN(Field2)
		READ_PARAM(INT1)
		READ_PARAM(DOUBLE1)
	DECLARE_PARAM_READER_END

	EXPECT_EQ(INT1,987654);
	EXPECT_FLOAT_EQ(DOUBLE1,0.0001);


}

